FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml ./pom.xml
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app
ENV TZ=Asia/Shanghai
COPY --from=build /app/target/*.jar /app/blog-backend.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/blog-backend.jar", "--spring.profiles.active=prod"]
